apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ys5v0dkwu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ys5v0dkwu-python 
  name: ys5v0dkwu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ys5v0dkwu-python 
